// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddExistingItemInVirtualFolder
{
    static class Vsix
    {
        public const string Id = "AddExistingItemInVirtualFolder.Sander Cox.6eb67602-1ce0-4a6f-82d4-9d6ccc2b6d72";
        public const string Name = "AddExistingItemInVirtualFolder";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Sander Cox";
        public const string Tags = "";
    }
}
